name: Test

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Show Foundry config
        run: forge config

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests (without fork)
        run: |
          # Run basic tests without requiring mainnet fork
          forge test --match-contract "Counter" -vvv
        id: test

      - name: Run Historical Bug tests (with fork)
        env:
          # Use a public RPC endpoint for CI
          ETH_RPC_URL: https://rpc.ankr.com/eth
        run: |
          # Run historical bug tests with fork
          forge test --match-contract "CompoundHistoricalBugs" --fork-url $ETH_RPC_URL -vv
        id: test-fork

      - name: Run Forge fmt
        run: forge fmt --check
        id: fmt